apiVersion: v1
kind: Service
metadata:
  name: github-service-app
spec:
  selector:
    app: github-service-app # matchLabels do deployment
  ports:
    - port: 8080 # porta do service
  type: NodePort # para poder acessar o pod externamente
---